version: '3.8'

services:
  source-db:
    image: mysql:8.2
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: Password@123456
      MYSQL_DATABASE: retail_db
    ports:
      - "3306:3306"
    restart: always

  target-db:
    image: postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Post@123456
      POSTGRES_DB: retail_db
    ports:
      - "5432:5432"
    restart: always